### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stark1tty**
Added archaeology to the list! Will edit with a signup google form link.

### CODE REVIEW

**Comment by nathanlesage** [comment]
Thank you! One thing though: We've switched to a GitHub Actions based Page builder, so right now the repository doesn't offer much for archaeologists. Do you know how to set up this? (I haven't yet had a chance to fully describe the steps on our main repo …)

**Comment by stark1tty** [comment]
Hi Nathan. I think my later edits should redirect to the page itself. Sorry for the multiple edits! I am learning as I go. :)

**Comment by stark1tty** [comment]
https://stark1tty.github.io/Mastodon-Archaeology/ This is what you are referring to I believe?

**Comment by nathanlesage** [comment]
Yes, that was what I was referring to! Thank you for updating the link – merging now! :)

**Pull request merged**
