### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rigard**
Add server for middle and high school design teachers

### CODE REVIEW

**Comment by nathanlesage** [comment]
Thank you for opening this PR! Is the server very new? I was wondering because there is no information about the server itself provided.

**Comment by rigard** [comment]
Hi. Yes, it's still brand new. Is there a base requirement to be added? Happy to oblige :)

**Comment by nathanlesage** [comment]
I feel that having a little bit of rules and intro to a server is always very nice to have for people that are looking for a server, to know if its suitable them or not! So it would be great if you could add that! :)

**Comment by rigard** [comment]
No problem. I've added a bit more content so it should be good now, and I will continue to do so.

**Comment by nathanlesage** [comment]
Looks good, thank you!

**Pull request merged**
