### PR TITLE
Add redNiboe to server list

### PR DESCRIPTION
**Pull request by jorgesat**

### CODE REVIEW

**Comment by nathanlesage** [comment]
Can it be that the server has crashed …?

**Comment by jorgesat** [comment]
hi, the server is running.

**Comment by nathanlesage** [comment]
Ah, now it works. Thank you for confirming! How does one ask for an invite to this server? Without that information, it may be difficult for people to approach whomever is managing the server. Is there some way for people to ask for an invite that we could add here so that people could look at the server and decide if it would be for them and then contact whomever is responsible for it?

**Comment by jorgesat** [comment]
Hi, people can apply for an invitation by sending an email to comunica@niboe.info. It is stated at https://red.niboe.info/about

**Comment by nathanlesage** [comment]
Alright, sorry for not spotting this earlier; I'm lacking in Spanish knowledge — merging!

**Pull request merged**
