### PR TITLE
added biophysics/biology related group + bots

### PR DESCRIPTION
**Pull request by jocelynetienne**

### CODE REVIEW

**Comment by nathanlesage** [comment]
Hey, I'm commenting to let you know I did not forget about your PR! We're just currently thinking about whether including bots in this list is a good or a not so good idea. Do you have any comments on which way we should lean in this regard? Do the bots bring some specific benefit that people would not bring? I am specifically thinking that the authors of the arXiv papers should hopefully be on one of the linked lists, thereby curating the content that those bots are pushing to Mastodon relatively unchecked. What is your stance on this?

**Comment by jocelynetienne** [comment]
Hi,

Yes, legitimate question. I've always felt frustrated with bots that just send the whole of an RSS flux. That's the case for my 2 bots named bioRxiv_... (although they toot only a subset of bioRxiv, so it makes about 10 toots/day - manageable if that's your field).

Then the other bots I've built are multiple-sources and keyword based. They harvest from 3 different sources (arXiv, nioRxiv and PubMed) and filter according to keywords, the most complex one being @mechanobio which tries to identify papers that focus on a bio-system but focus on its mechanical function. They add hashtags which are harvested from the abstract.

So yes, I think these bots are bringing something no human user could do. Of course, they can and will make errors and also occasionally toot garbage, I guess, but probably not much more than a human user.

**Comment by nathanlesage** [comment]
Hmm … @trutzig89182 What do you think about this?

**Comment by nathanlesage** [comment]
Alright, gonna merge it now, I mean there's no harm in just showing people these options, nobody has to use them. I will add a small warning, though.

**Pull request merged**
