### PR TITLE
Added hashtags

### PR DESCRIPTION
**Pull request by trutzig89182**

### CODE REVIEW

**Comment by nathanlesage** [comment]
Mh. I'm not sure what the added benefit of these hashtags might be …? Especially since we can't really link them as they're server-specific?

**Comment by trutzig89182** [comment]
I aggree. People asked for it repeatedly, so I though adding them at the end would not do any bad. But in the way I phrased that you may read, that I am not 100 % seeing the point. But, others might? You decide. 

The suggestion to include servers makes more sense to me, anyway.

**Comment by nathanlesage** [comment]
Yeah, I just merged the servers. I think, regarding hashtags: Those will develop much more naturally, so the list of hashtags would possibly be outdated very soon, while the researchers (hopefully) will do their thing much longer!

**Comment by trutzig89182** [comment]
The only reason why i had them, is that there are some very generic # like #histodons, that will likely hold for a while, and I didn’t want to force people to make a group to be on the list, when the successfully to something similar via hahstags. But perhaps we can collect them in an issue, and should be decide to include them at some later point, we already have it all together.

**Comment by nathanlesage** [comment]
Yes, we can definitely continue to observe how hashtags are being used on Mastodon and reevaluate then!

**Pull request closed without merging**
