### PR TITLE
adding AI people

### PR DESCRIPTION
**Pull request by cerisara**
Just built the AI page, still to be improved.

### CODE REVIEW

**Comment by nathanlesage** [comment]
Looks good, thank you!

**Comment by logological** [comment]
I don't think this pull request should have been accepted, since the licence it uses is incompatible with the one for this repository.  (Theirs states that the list "can only be used with explicit permission by the repository owner", whereas this one says that the list is licensed under CC BY-NC 4.0.)  Since their list was forked from the Archaeology list, that one (and any others forked from it and submitted here) may have the same problem.

@cerisara, if your list is entirely your own work, then perhaps you should change the licence to CC BY-NC 4.0 or one compatible with it.  That would be a better way of resolving the issue.

**Comment by nathanlesage** [comment]
The sentence you refer to only attempts to ensure the data in the list. Also, linking the list here in no way constitutes a license problem, since it constitutes more of a citation; we do not use or reuse any content in there on purpose, so I do not think any list here -- including this one -- poses a problem regarding license.

**Comment by cerisara** [comment]
> CC BY-NC 4.0

OK, I changed the license as suggested.

**Pull request merged**
