### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stark1tty**
fixed typo added Theologidons

### CODE REVIEW

**Comment by nathanlesage** [comment]
Is there also the Google Sheet where the form data ends up on? Or is that the linked Google Form? I'm not completely certain I understand how they relate 🙈

**Comment by stark1tty** [comment]
Oops, let me sort that.

**Comment by stark1tty** [comment]
Fixed!

**Comment by nathanlesage** [comment]
Perfect, thanks! I've only replaced the shortened link with the full one (for a11y, transparency, & because we aren't limited by character counts here!)

**Pull request merged**
