### PR TITLE
Add HPC.social

### PR DESCRIPTION
**Pull request by alansill**
Add link to high performance computing and related fields survey (for now, will be replaced by a link to the full server when it comes up).

Thanks for doing this!

### CODE REVIEW

**Comment by nathanlesage** [comment]
Thank you for your initiative!

Since this is merely a survey right now, I can understand that it makes sense to add a link here on this central, well-known place. However, I wouldn't directly put it into the list of servers, but rather below. Here's a wording suggestion, feel free to adapt if necessary:

> If you are working in or with HPC and would like to join a dedicated Mastodon server, [Dr. Alan Sill (Texas Tech University)](https://github.com/alansill) is currently running a survey to estimate interest. You can find the survey at [survey.hpc.social](https://survey.hpc.social).

**Comment by alansill** [comment]
You can if you want -- I made the pull request modifiable -- but the full site will likely be up within a week or two. Meanwhile community input in shaping decisons with respect to the server setup is valuable.

> Thank you for your initiative!
> 
> 
> 
> Since this is merely a survey right now, I can understand that it makes sense to add a link here on this central, well-known place. However, I wouldn't directly put it into the list of servers, but rather below. Here's a wording suggestion, feel free to adapt if necessary:
> 
> 
> 
> > If you are working in or with HPC and would like to join a dedicated Mastodon server, [Dr. Alan Sill (Texas Tech University)](https://github.com/alansill) is currently running a survey to estimate interest. You can find the survey at [survey.hpc.social](https://survey.hpc.social).

**Comment by nathanlesage** [comment]
Yeah, that's kind of my question: We can either do two PRs – one with the survey now and then with the server once it's set up – or only one, adding the server once it's done. I'm fine with both options, but I'd say adding the survey here would give it more exposure so you get more feedback, right?

**Comment by alansill** [comment]
Yes, adding the survey now would help with exposure and doesn't seem to conflict with any other existing entries. 

The update replacing it with the full site should be within a couple of weeks if all works out.

**Comment by nathanlesage** [comment]
Alright, adapted wording, will merge now! Please open a PR once the server is live! :)

**Pull request merged**
